package report

import (
	"fmt"
	"sort"
	"strings"

	"github.com/KranzL/omni-example/internal/bench"
)

const maxAnswerText = 70

func kind(c Config) string {
	if c.Baseline {
		return "baseline"
	}
	return "router"
}

func money(v float64) string {
	return fmt.Sprintf("$%.4f", v)
}

func ratio(n, total int) string {
	if total == 0 {
		return "-"
	}
	return fmt.Sprintf("%.3f (%d/%d)", float64(n)/float64(total), n, total)
}

func passesText(n int) string {
	if n == 1 {
		return "1 pass"
	}
	return fmt.Sprintf("%d passes", n)
}

func difficultyCell(c Config, ds bench.DifficultySummary) string {
	if p := c.Passes(); p > 1 {
		return fmt.Sprintf("%d/%d (%s)", ds.Correct, ds.Total, passesText(p))
	}
	return fmt.Sprintf("%d/%d", ds.Correct, ds.Total)
}

func TierMix(c Config) string {
	if c.Baseline {
		return "-"
	}
	parts := make([]string, len(Tiers))
	for i, t := range Tiers {
		parts[i] = fmt.Sprintf("%.0f", 100*c.TierMix[t])
	}
	return strings.Join(parts, "/")
}

func Table(cs []Config) string {
	var sb strings.Builder
	sb.WriteString("| config | kind | passes | accuracy | strict | easy | moderate | hard | expert | total cost | routing overhead | cost per correct | mean latency | p95 latency | cache hit | tier mix cheap/mid/top % |\n")
	sb.WriteString("|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|\n")
	for _, c := range cs {
		s := c.Summary
		fmt.Fprintf(&sb, "| %s | %s | %d | %s | %s |", c.Label, kind(c), c.Passes(), ratio(s.Correct, s.Total), ratio(s.CorrectStrict, s.Total))
		for _, d := range Difficulties {
			ds, ok := s.ByDifficulty[d]
			if !ok || ds.Total == 0 {
				sb.WriteString(" - |")
				continue
			}
			fmt.Fprintf(&sb, " %s |", difficultyCell(c, ds))
		}
		fmt.Fprintf(&sb, " %s | %s | %s | %.1fs | %.1fs | %.2f | %s |\n",
			money(c.CostUSD), money(s.RouteCostUSD), fmt.Sprintf("$%.5f", c.CostPerCorrect()),
			s.MeanLatencyMS/1000, float64(s.P95LatencyMS)/1000, c.CacheHitRatio, TierMix(c))
	}
	return sb.String()
}

func Headline(cs []Config) string {
	var sb strings.Builder
	full := Comparable(cs)
	n := FullSetSize(cs)
	if best, ok := Cheapest(full); ok {
		fmt.Fprintf(&sb, "Lowest cost per correct answer on the full %d-question set: %s at $%.5f (%d/%d correct over %s, total $%.4f).\n", n, best.Label, best.CostPerCorrect(), best.Summary.Correct, best.Summary.Total, passesText(best.Passes()), best.CostUSD)
	}
	for _, p := range providers(full) {
		if best, ok := Cheapest(byProvider(full, p)); ok {
			fmt.Fprintf(&sb, "Lowest on %s: %s at $%.5f (%d/%d correct).\n", p, best.Label, best.CostPerCorrect(), best.Summary.Correct, best.Summary.Total)
		}
	}
	front := Frontier(full)
	for _, p := range providers(full) {
		var names []string
		for _, c := range sortByCost(byProvider(full, p)) {
			if front[c.Label] {
				names = append(names, fmt.Sprintf("%s (%s per pass, %.3f)", c.Label, money(c.PassCostUSD()), c.Summary.Accuracy))
			}
		}
		fmt.Fprintf(&sb, "Pareto frontier on %s, cheapest first: %s.\n", p, strings.Join(names, ", "))
	}
	return sb.String()
}

func providers(cs []Config) []string {
	seen := map[string]bool{}
	var out []string
	for _, c := range cs {
		if !seen[c.Provider] {
			seen[c.Provider] = true
			out = append(out, c.Provider)
		}
	}
	sort.Strings(out)
	return out
}

func byProvider(cs []Config, p string) []Config {
	var out []Config
	for _, c := range cs {
		if c.Provider == p {
			out = append(out, c)
		}
	}
	return out
}

func sortByCost(cs []Config) []Config {
	out := append([]Config(nil), cs...)
	sort.SliceStable(out, func(i, j int) bool { return out[i].PassCostUSD() < out[j].PassCostUSD() })
	return out
}

func Markdown(cs []Config) string {
	var sb strings.Builder
	n := FullSetSize(cs)
	sb.WriteString("# Cost versus accuracy\n\n")
	fmt.Fprintf(&sb, "Generated by harness report from %d results/**/latest.json files and the run files they point at. Do not edit by hand; rerun harness report.\n\n", len(cs))
	sb.WriteString(Headline(cs))
	sb.WriteString("\n## Summary\n\n")
	sb.WriteString(Table(cs))
	sb.WriteString("\n")
	sb.WriteString(columnNotes(cs, n))
	sb.WriteString("\n## Charts\n\n")
	fmt.Fprintf(&sb, "![Total cost versus accuracy](%s)\n\n", ParetoFile)
	fmt.Fprintf(&sb, "![Accuracy by difficulty per configuration](%s)\n\n", DifficultyFile)
	sb.WriteString("## Regraded verdicts\n\n")
	sb.WriteString(regradeSection(cs))
	sb.WriteString("\n## Wrong answers\n\n")
	sb.WriteString(wrongSection(cs))
	return sb.String()
}

func columnNotes(cs []Config, full int) string {
	var sb strings.Builder
	sb.WriteString("Columns. accuracy is the lenient verdict, strict the exact-format verdict. total cost is agent plus routing plus judge cost in USD for the whole run. routing overhead is the part spent on routing decisions and verifiers. cost per correct is total cost over lenient correct answers. cache hit is cache-read input tokens over all agent input tokens. tier mix is the share of questions whose final answer came from each tier; baselines use one tier.\n\n")
	var partial []string
	for _, c := range cs {
		if q := c.Questions(); q != full {
			partial = append(partial, fmt.Sprintf("%s (%d)", c.Label, q))
		}
	}
	if len(partial) > 0 {
		fmt.Fprintf(&sb, "Runs on fewer than %d questions are left out of the Pareto chart and the lowest-cost pick: %s.\n", full, strings.Join(partial, ", "))
	}
	return sb.String()
}

func regradeSection(cs []Config) string {
	var sb strings.Builder
	var regraded, not []string
	changed := 0
	var lines []string
	for _, c := range cs {
		r := c.Summary.Regraded
		if r == nil {
			not = append(not, c.Label)
			continue
		}
		regraded = append(regraded, c.Label)
		if r.VerdictsChanged+r.StrictChanged == 0 {
			continue
		}
		changed++
		var ids []string
		for _, ch := range r.Changes {
			ids = append(ids, fmt.Sprintf("%s %s %t to %t", ch.ID, ch.Field, ch.From, ch.To))
		}
		lines = append(lines, fmt.Sprintf("- %s, regraded %s: %d correct and %d correct_strict verdicts changed (%s)", c.Label, r.At, r.VerdictsChanged, r.StrictChanged, strings.Join(ids, "; ")))
	}
	fmt.Fprintf(&sb, "harness bench regrade --verdicts recomputes correct and correct_strict with the current grader without touching the recorded answers. %d of the %d configurations above were regraded; %d had verdicts change:\n\n", len(regraded), len(cs), changed)
	if len(lines) == 0 {
		sb.WriteString("- none\n")
	}
	for _, l := range lines {
		sb.WriteString(l + "\n")
	}
	if len(not) > 0 {
		fmt.Fprintf(&sb, "\nNot regraded: %s.\n", strings.Join(not, ", "))
	}
	return sb.String()
}

func wrongSection(cs []Config) string {
	var sb strings.Builder
	sb.WriteString("Questions each configuration got wrong under the lenient grader, with the fail reason from internal/bench/reason.go.\n")
	for _, c := range cs {
		fmt.Fprintf(&sb, "\n### %s\n\n", c.Label)
		if len(c.Wrong) == 0 {
			sb.WriteString("None.\n")
			continue
		}
		sb.WriteString("| question | difficulty | repeat | tier | reason | answer |\n|---|---|---|---|---|---|\n")
		for _, l := range c.Wrong {
			reason := l.FailReason
			if reason == "" {
				reason = bench.ReasonCode(l.Error)
			}
			fmt.Fprintf(&sb, "| %s | %s | %d | %s | %s | %s |\n", l.ID, l.Difficulty, l.Repeat, l.Tier, cell(reason, 160), cell(l.Answer, maxAnswerText))
		}
	}
	return sb.String()
}

func cell(s string, n int) string {
	s = strings.Join(strings.Fields(s), " ")
	if r := []rune(s); len(r) > n {
		s = string(r[:n]) + "..."
	}
	s = strings.ReplaceAll(s, "|", "\\|")
	if s == "" {
		return "-"
	}
	return s
}

func ReadmeSection(cs []Config) string {
	var sb strings.Builder
	sb.WriteString("Regenerate with harness report. The full report and the two charts are written locally to results/, which keeps them out of git.\n\n")
	sb.WriteString(Headline(cs))
	sb.WriteString("\n")
	sb.WriteString(Table(cs))
	return sb.String()
}
